#!/bin/bash

read -p "You're about toush, are you sure you won't break the build? " -n 1 -r < /dev/tty
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    exit 0 #ush will execute
fi
exit 1 #ush will not execute
